### ISSUE TITLE
Tips and tricks

### ISSUE THREAD

**Issue by kforsgren** [potifarfar-soft/dnd5e-digital-character#17]
Since I am a visual studio/ms-monkey I thought it would be preferrable to get some tips for react/node development.

Like, for example, @Muthaias  what IDE do you recommend? Sublime text?
Typescript compilation via npm?

I guess it's up to personal preferences but could be good to share some tips

**Comment by fredrik-hjarner** [comment]
> what IDE do you recommend?

Visual Studio Code is quite nice. Both TypeScript and VS Code is made by Microsoft.

**Comment by Muthaias** [comment]
I totally agree with Fredrik. Visual Studio Code is nice. And when it comes to building code with react the alternatives are quite a few but for some reason most JS build environments are based on command line tools and node. Don't ask me why and there's surely other options but I haven't really looked into it. 

Getting started with react is very simple. Just check out this very short guide: https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

The last step would be getting started with SASS/SCSS which slightly different and requires amoung other things an installation of ruby. Use it once and you'll never want to use regular CSS again ;)

https://sass-lang.com/install

**Comment by kforsgren** [comment]
Nice, I'll familiarize myself!
