### ISSUE TITLE
Grupp?

### ISSUE THREAD

**Issue by fredrik-hjarner** [potifarfar-soft/dnd5e-digital-character#2]
Jag vet inte men kan det vara en bra idé att ha en grupp under vilken man kan ha flera projekt?

T ex [potifarfar-soft](https://github.com/potifarfar-soft)

Otherwise some one of us has to *own* each project. A group allows several project to be at the same place, i.e. the _group_ owns it.

**Comment by robbiten** [comment]
Sounds good. I'm trying to figure out how everything works here. How do you create a group? Also, is it possible to move this repo to this new group? I know it's newly created, im just curious if it can be done :stuck_out_tongue_winking_eye: 
Ja jag kör allt på engelska i fortsättningen, det är fett mycket mer coolt :wink:

**Comment by fredrik-hjarner** [comment]
![image](https://user-images.githubusercontent.com/35084243/35199236-c7ce0f08-fefb-11e7-8e45-95682c7faee4.png)

**Comment by fredrik-hjarner** [comment]
Haven't transferred a repository before but there is some info about it here:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by Muthaias** [comment]
Cool stuff!

**Comment by robbiten** [comment]
Okay, I'll try to transfer this repo to our organization, seems to be pretty straight forward :crossed_fingers:

**Comment by robbiten** [comment]
Great success! Closing issue :tada:

**Comment by fredrik-hjarner** [comment]
Oh nice! 👍
