### ISSUE TITLE
Create a specification for the MVP of a character sheet

### ISSUE THREAD

**Issue by Muthaias** [potifarfar-soft/dnd5e-digital-character#4]
In order to begin work we need to determine the minimum viable product. An MVP specification should be a good start when creating more issues and milestones.

**Comment by kforsgren** [comment]
MVP points:

1. All custom values on the sheet can be filled in and stored (e.g. Str, Dex, Con)
2. Values which are calculated are shown (e.g. skill checks, attack bonii)
3. A database or API for the ruleset is implemented to be able to calculate or fill in some values from 2. Including equipment stats.
To be continued...
 
Ideas:
- The HP value should be easily changed. For example a list of common damage numbers (for that level, customizeable?) the user can choose from so one does not always have to input numbers.

**Comment by robbiten** [comment]
About @kforsgren idea about easily changed HP values, same principle could apply for other things like XP, coins and ammunition as well. 

What do you guys think about integrating dice rolls in the application? Maybe it's more of a matter for post MVP implementation?

**Comment by robbiten** [comment]
I've got some nice ideas for more features, but we should discuss it further on our kick off meeting. I don't think they should be a part of the MVP but more something that you could be added later on.

- Equipment sharing. Players and DM could hand equipment and coins to each other. 
- A small note sharing feature, or a "chat". Not at all a vital feature, quite the opposite really, just fancy. DM could for example send a note to a player "Reinwald is showing just a bit too much hospitality for you to feel comfortable..."

**Comment by fredrik-hjarner** [comment]
> MVP points:
> 
> All custom values on the sheet can be filled in and stored (e.g. Str, Dex, Con)
> Values which are calculated are shown (e.g. skill checks, attack bonii)
> A database or API for the ruleset is implemented to be able to calculate or fill in some values from 2. Including equipment stats.
> To be continued...

Yes.

> Ideas:
> 
> The HP value should be easily changed. For example a list of common damage numbers (for that level, customizeable?) the user can choose from so one does not always have to input numbers.

I don't understand this point

**Comment by fredrik-hjarner** [comment]
> A small note sharing feature, or a "chat". Not at all a vital feature, quite the opposite really, just fancy. DM could for example send a note to a player "Reinwald is showing just a bit too much hospitality for you to feel comfortable..."

I would be nice to have it integrated, **but** In my opinion that could be made via a normal sms. As an optional feature maybe

**Comment by fredrik-hjarner** [comment]
> Equipment sharing. Players and DM could hand equipment and coins to each other.

In my opinion a good idea. I am insane so I'd actually like things such as every every transferral (or creation)  saved with a timestamp (and from/to info) so you can follow exactly what the fuck happened with a specific item.
I dont know how useful that would be, but I think that in some situation that can aid the DM _a la_ "The curse kicks in after wearing the ring in a week, but how the f long have the character been wearing it.. let's check the **log**"

**Comment by robbiten** [comment]
>> Ideas:

>> The HP value should be easily changed. For example a list of common damage numbers (for that level, customizeable?) the user can choose from so one does not always have to input numbers.

> I don't understand this point

When I read it I was thinking something like setting the android [alarm clock](https://i.stack.imgur.com/WCET2.png) . Instead of entering the time by the "numpad" an "hour wheel" appears. After selecting the hour the wheel reshapes and let you select minutes. Something similar could be used when entering hp loss or hp gain on the character sheet.
